In [1]:
import tensorflow as tf
from tensorflow.keras import models,layers 
import os
from PIL import Image
import numpy as np

# Load Data

In [2]:
i=0

os.chdir('Potato_data\Potato___Early_blight')
X_train=os.listdir()
for image in X_train:
    X_train[i]=Image.open(image)
    i+=1
Y_train=[0]*len(os.listdir())

os.chdir('..')
os.chdir('Potato___healthy')
X_train+=os.listdir()
while(i<len(X_train)):
    X_train[i]=Image.open(X_train[i])
    i+=1
Y_train+=[1]*len(os.listdir())

os.chdir('..')
os.chdir('Potato___Late_blight')
X_train+=os.listdir()
while(i<len(X_train)):
    X_train[i]=Image.open(X_train[i])
    i+=1
Y_train+=[2]*len(os.listdir())

os.chdir('../..')

temp_xtrain=X_train
temp_ytrain=Y_train
print(len(X_train))
print(len(Y_train))

print(type(X_train[0]))

2146
2146
<class 'PIL.JpegImagePlugin.JpegImageFile'>


In [3]:
print((np.array(X_train[0])).shape)
print(np.array(X_train[0]))

(256, 256, 3)
[[[187 186 200]
  [174 173 187]
  [168 167 181]
  ...
  [136 134 147]
  [127 125 138]
  [149 147 160]]

 [[180 179 193]
  [201 200 214]
  [225 224 238]
  ...
  [146 144 157]
  [135 133 146]
  [135 133 146]]

 [[198 197 211]
  [172 171 185]
  [176 175 189]
  ...
  [147 145 158]
  [147 145 158]
  [134 132 145]]

 ...

 [[167 165 179]
  [167 165 179]
  [168 166 180]
  ...
  [151 148 159]
  [143 140 151]
  [149 146 157]]

 [[149 147 161]
  [153 151 165]
  [157 155 169]
  ...
  [125 122 133]
  [117 114 125]
  [130 127 138]]

 [[165 163 177]
  [165 163 177]
  [164 162 176]
  ...
  [131 128 139]
  [140 137 148]
  [119 116 127]]]


In [4]:
(np.array(X_train[0]))[0][0] #this show first pixel of image and we know pixel contan RGB values (0-255) which shows here 

array([187, 186, 200], dtype=uint8)

In [5]:
print((np.array(X_train[0])).shape)
for i in range(len(X_train)):
     X_train[i]=np.array(X_train[i])

X_train=np.array(X_train)
Y_train=np.array(Y_train)

(256, 256, 3)


# Splitting Data

In [6]:
# If your labels are integers (e.g., 0, 1, 2)
Y_train = tf.keras.utils.to_categorical(Y_train, num_classes=3)

In [7]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X_train,Y_train,test_size=0.3,shuffle=True)

In [8]:
model=models.Sequential([
    layers.Conv2D(64,kernel_size=(3,3),padding='same',activation='relu',input_shape=((256, 256, 3,))),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(96,kernel_size=(3,3),padding='same',activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(128,kernel_size=(3,3),padding='same',activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(164,kernel_size=(3,3),padding='same',activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    
    layers.Dense(64,activation='relu'),
    layers.Dense(28,activation='relu'),
    layers.Dense(3,activation='softmax')
])
model.compile(loss='CategoricalCrossentropy',optimizer='adam',metrics=['accuracy'])

In [9]:
model.fit(x_train,y_train,epochs=15)
#History=model.fit(x_train,y_train,epochs=15) #after eecution of code istory object contain information about training process

Epoch 1/15


47/47 [==============================] - 209s 4s/step - loss: 4.6978 - accuracy: 0.5679
Epoch 2/15
47/47 [==============================] - 196s 4s/step - loss: 0.4963 - accuracy: 0.8176
Epoch 3/15
47/47 [==============================] - 2778s 60s/step - loss: 0.3251 - accuracy: 0.8782
Epoch 4/15
47/47 [==============================] - 389s 8s/step - loss: 0.2733 - accuracy: 0.9035
Epoch 5/15
47/47 [==============================] - 240s 5s/step - loss: 0.1960 - accuracy: 0.9334
Epoch 6/15
47/47 [==============================] - 164s 3s/step - loss: 0.1303 - accuracy: 0.9494
Epoch 7/15
47/47 [==============================] - 166s 4s/step - loss: 0.2373 - accuracy: 0.9201
Epoch 8/15
47/47 [==============================] - 189s 4s/step - loss: 0.1639 - accuracy: 0.9461
Epoch 9/15
47/47 [==============================] - 194s 4s/step - loss: 0.1784 - accuracy: 0.9348
Epoch 10/15
47/47 [==============================] - 195s 4s/step - loss: 0.0870 - accuracy: 0.9687
Epoch

In [10]:
y_predicted=model.predict(x_test)

21/21 [==============================] - 15s 634ms/step


In [11]:
y_predicted

array([[9.9999976e-01, 4.4186484e-19, 1.8471339e-07],
       [4.7140857e-05, 6.9174927e-01, 3.0820361e-01],
       [9.9999964e-01, 1.2720718e-21, 3.4000402e-07],
       ...,
       [1.9485024e-05, 8.7238425e-01, 1.2759623e-01],
       [1.0000000e+00, 2.4558312e-13, 4.7559229e-08],
       [3.5730515e-08, 7.0552324e-04, 9.9929440e-01]], dtype=float32)

In [12]:
y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [13]:
loss,accuracy=model.evaluate(x_test,y_test)

21/21 [==============================] - 14s 631ms/step - loss: 0.3434 - accuracy: 0.9053


In [14]:
print('Loss:',loss*100)
print('Accuracy:',accuracy*100)

Loss: 34.340545535087585
Accuracy: 90.52795171737671
